# Site settings
title: Gyula Nagy
email: gyula.nagy.baritone@gmail.com
url: https://tamaslang.github.io/gyulanagy.com
description: "Baritone, Opera and Oratorio Singer"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://uk.linkedin.com/in/gyula-nagy

# Build settings
markdown: kramdown
permalink: pretty
